# Generated by Django 5.0.2 on 2024-03-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['custom_id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['custom_id']},
        ),
    ]
