# Generated by Django 5.0.2 on 2024-03-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='template',
        ),
    ]
