# Generated by Django 5.0.2 on 2024-03-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='project_items', to='portfolio.item'),
        ),
    ]
