# Generated by Django 5.0.2 on 2024-03-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(blank=True, to='portfolio.link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='items',
            field=models.ManyToManyField(blank=True, to='portfolio.item'),
        ),
    ]
